3 New Enchants, 13 Rebuilt
Auxilor/EcoEnchants pull request #294
Opened 2022-09-04 21:06 UTC by btjt97

2022-09-04 23:09 UTC, MillionthOdin16 requested changes
Tweak smelting effect

2022-09-04 23:09 UTC, MillionthOdin16 commented on eco-core/core-plugin/src/main/resources/enchants/smelting.yml
> +
Pretty sure you need a item drop event trigger

effects:
  - id: autosmelt
    args:
      drop_xp: true
    triggers:
      - block_item_drop

2022-09-04 23:33 UTC, MillionthOdin16 commented
Did you even test these? Loading these enchants in the beta clearly shows configuration errors. Mostly doing with missing triggers.
For example:

`[EcoEnchants] Invalid configuration for damage_multiplier in context Enchantment endinfusion:  
[EcoEnchants] (Cause) Argument 'triggers'  
[EcoEnchants] (Reason) Specified effect requires at least 1 trigger`

2022-09-05 12:37 UTC, WillFP commented
You didn't test these before PRing?

2022-09-05 14:01 UTC, MillionthOdin16 commented
@btjt97 I submitted a PR to you that has updates with fixes. Stab enchant looked pretty misconfigured, so I removed it.

2022-09-05 14:07 UTC, closed without merging